# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e23a5754adddf8997e90201f4bc45cdd08ef57ec5bdfbeadc0e38d290b3130155ea2da1f94e6c3e8f2bea5b19dd35b313492fc090eb9f22b0f37a66b85dab930

test:
  secret_key_base: 6fe334754ef2d7f95e79763a2c73209ab5dc3c64c2d94c2576d87355d67a6ef0b58443774dcb7bc6286bfea77e348f38f6736d90a73950c856393d4886ed35e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
